dist: xenial

language: python

addons:
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=1.11,<2.0"
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django==2.2b1"

matrix:
  exclude:
  - python: "3.4"
    env: DJANGO="django>=2.1,<2.2"
  - python: "3.4"
    env: DJANGO="django==2.2b1"
  - python: "3.7"
    env: DJANGO="django>=1.11,<2.0"

install:
  - pip install pip pipenv -U
  - pipenv install "$DJANGO" --skip-lock
  - pipenv install --dev --skip-lock
script:
  - make qa
  - make coverage
after_success:
  - codecov
