# Force the use of the new container-based infrastructure
sudo: false

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.9,<1.10"
  - DJANGO="django>=1.10,<1.11"
  - DJANGO="django>=1.11,<2.0"

matrix:
  allow_failures:
    - python: "3.7-dev"
  exclude:
  - python: "3.3"
    env: DJANGO="django>=1.9,<1.10"
  - python: "3.3"
    env: DJANGO="django>=1.10,<1.11"
  - python: "3.3"
    env: DJANGO="django>=1.11,<2.0"
install:
  - "pip install $DJANGO"
script:
  - make travis
after_success:
  - codecov
