# Force the use of the new container-based infrastructure
sudo: false

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - DJANGO="django>=1.11,<2.0"
  - DJANGO="django>=2.0,<2.1"

matrix:
  allow_failures:
    - python: "3.7-dev"
  exclude:
  - python: "2.7"
    env: DJANGO="django==2.0a1"
install:
  - "pip install $DJANGO"
script:
  - make travis
after_success:
  - codecov
